"""Initial migration.

Revision ID: 11db57b29afb
Revises: 7e43f44c06e7
Create Date: 2024-08-06 15:36:28.485305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11db57b29afb'
down_revision = '7e43f44c06e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booked_space', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=False))

    with op.batch_alter_table('space', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('space', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=20), nullable=True))

    with op.batch_alter_table('booked_space', schema=None) as batch_op:
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
