"""Initial migration.

Revision ID: 802460afb65e
Revises: 11db57b29afb
Create Date: 2024-08-06 16:07:42.650407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802460afb65e'
down_revision = '11db57b29afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booked_space', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    with op.batch_alter_table('space', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('space', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('price')

    with op.batch_alter_table('booked_space', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.DATETIME(), nullable=False))
        batch_op.drop_column('price')

    # ### end Alembic commands ###
