"""Initial migration.

Revision ID: c0655e96b642
Revises: 3e01b164a432
Create Date: 2024-08-06 14:26:45.494134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0655e96b642'
down_revision = '3e01b164a432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booked_space', schema=None) as batch_op:
        batch_op.drop_column('start_time')
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booked_space', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
